import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <nav className="sticky flex top-0 z-50 bg-orange-200 text-black p-4 space-x-5 w-full">
        <Link href="/" className="hover:text-gray-600">Home</Link>
        <Link href="/api" className="hover:text-gray-600">API</Link>
        <Link href="/visualization" className="hover:text-gray-600">Visualization</Link>
      </nav>
        {children}
      </body>
    </html>
  );
}
