name: Selenium and API tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install

      - name: Start frontend server
        run: npm run dev &
        env:
          NODE_ENV: development

      - name: Install wait-on
        run: npm install -g wait-on
      
      - name: Wait until frontend returns correct content
        run: wait-on http://localhost:3000 --timeout 30000
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium and API tests
        run: |
          cd tests
          pytest test_website.py
        
