name: Selenium and API tests

on: [push, pull_request]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install selenium
          pip install chromedriver-autoinstaller

      - name: Run Selenium and API tests
        run: python -m unittest tests/test_website.py
